version: '3'
services:
  myapplication:
    image: myapp:1.0
    environment: 
      - MONGODB_CONNSTRING=mongodb://testing:testing@mongodb
    ports:
      - 80:80
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testing
      - MONGO_INITDB_ROOT_PASSWORD=testing
    ports:
      - 3000:3000
  broker:
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
    ports:
      - "1883:1883"